version: "3"

services:
  sparkwebserver:
    build:
      context: .
      dockerfile: DockerfileServer
    ports:
      - "4567:4567"

  logservice1:
    build:
      context: .
      dockerfile: DockerfileService
    ports:
      - "35001:35000" # Puerto interno del contenedor

  logservice2:
    build:
      context: .
      dockerfile: DockerfileService
    ports:
      - "35002:35000" # Puerto interno del contenedor

  logservice3:
    build:
      context: .
      dockerfile: DockerfileService
    ports:
      - "35003:35000" # Puerto interno del contenedor

  db:
    image: mongo:3.6.1
    container_name: db
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - 27017:27017
    command: mongod

volumes:
  mongodb:
  mongodb_config:
